#include "common/list.h"

#include <stdio.h>

// Given a word, write a function to generate all of its unique generalized
// abbreviations.
// A generalized abbreviation of a word can be generated by replacing each
// substring of the word with the count of characters in the substring. Take the
// example of “ab” which has four substrings: “”, “a”, “b”, and “ab”. After
// replacing these substrings in the actual word by the count of characters, we
// get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
// Note: All contiguous characters should be considered one substring,
// e.g., we can’t take “a” and “b” as substrings to get “11”; since “a” and “b”
// are contiguous,
// we should consider them together as one substring to get an abbreviation “2”.
//
// Example 1:
// Input: "BAT"
// Output: "BAT", "BA1", "B1T", "B2", "1AT", "1A1", "2T", "3"
//
// Example 2:
// Input: "code"
// Output: "code", "cod1", "co1e", "co2", "c1de", "c1d1", "c2e", "c3", "1ode",
// "1od1", "1o1e", "1o2", "2de", "2d1", "3e", "4"
// Constraints:
//
// 1 <= word.length <= 15
// word consists of only lowercase English letters.

// generateGeneralizedAbbreviation returns all abbreviations for the given word

// generate_abbreviation_recursive is a recursive helper function to generate
// abbreviations. ab_word is the abbreviation built so far; it is copied
// before being changed, so each call keeps its own version.
void generate_abbreviation_recursive
(
    const char *word,
    const char *ab_word,
    int start,
    int count,
    StrList *result
)
{
    int word_len = (int)strlen(word);
    // room for the abbreviation so far, one more count, and one more letter
    char next[128];
    if (start == word_len)
    {
        if (count != 0)
        {
            snprintf(next, sizeof(next), "%s%d", ab_word, count);
            strlist_push(result, next);
        }
        else
        {
            strlist_push(result, ab_word);
        }
    }
    else
    {
        // continue abbreviating by incrementing the current abbreviation
        // count
        generate_abbreviation_recursive(word, ab_word, start + 1, count + 1,
                                        result);

        // restart abbreviating, append the count and the current character to
        // the string
        if (count != 0)
        {
            snprintf(next, sizeof(next), "%s%d%c", ab_word, count, word[start]);
        }
        else
        {
            snprintf(next, sizeof(next), "%s%c", ab_word, word[start]);
        }
        generate_abbreviation_recursive(word, next, start + 1, 0, result);
    }
}

// The abbreviations are returned in a list that the caller must free.
StrList generate_generalized_abbreviation
(
    const char *word
)
{
    StrList result = {0};
    generate_abbreviation_recursive(word, "", 0, 0, &result);
    return result;
}
